url: http://purchasingtoolpak.com
baseurl: 

# Site settings
title: Procurement Templates & Tools
email: purchasingtoolpak@gmail.com
description: Procurement templates that increase purchasing power. Excel purchase order, requisition, rfq, rfp, contract.

# was gems:
plugins:
 # jekyll-sitemap
  
# Google Services
  google_analytics: UA-86996516-1

# Team names, titles and social links
people:
- name: David Mak
  pic: 1
  position: Lead Designer
  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/purchasingtoolpak/purchasingtoolpak

# Postal address (add as many lines as necessary)
address:
  - line: 101 Oak Island Drive
  - line: Oak Island, NC 28465

# Build settings
markdown: kramdown
permalink: pretty
