url: http://purchasingtoolpak.com
baseurl: 

# Site settings
title: Purchasing Toolpak LLC
email: purchasingtoolpak@gmail.com
description: Free procurement templates and purchasing templates that increase buyer productivity, increase purchasing power, drive continuous improvement, quality improvement and manage supply and supplier risk.
keywords: procurement templates, purchasing templates

gems:
 # jekyll-sitemap
  
# Google Services
  google_analytics: UA-86996516-1

# Team names, titles and social links
people:
- name: David Mak
  pic: 1
  position: Lead Designer
  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: http://github.com/purchasingtoolpak/purchasingtoolpak

# Postal address (add as many lines as necessary)
address:
  - line: 101 Oak Island Drive
  - line: Oak Island, NC 28465

# Build settings
markdown: kramdown
permalink: pretty
